### ISSUE TITLE
CONSTRUCCION DE BACKEND

### ISSUE THREAD

**Issue by ChristianRivera31** [ISCOUTB/DH-MI-SUPERTIENDA#2]

**Comment by RUBENNN20** [comment]
Construcción un Backend en Dart (el backend del proyecto original esta en proceso)
En este proyecto, construí un backend utilizando el lenguaje de programación Dart y el paquete shelf, que sirve para crear servidores HTTP y APIs. 

Primero, inicié un nuevo proyecto Dart y configuré las dependencias necesarias. En el archivo pubspec.yaml, añadí la dependencia de shelf, que me permitió manejar las solicitudes HTTP y crear un servidor básico.
![Image](https://github.com/user-attachments/assets/f7a20609-6f2d-48b3-bd65-7a2414be61df)

A continuación, desarrollé el servidor en el archivo server.dart. Implementé un middleware para manejar CORS, lo que es fundamental para permitir que el backend acepte solicitudes de diferentes orígenes.
![Image](https://github.com/user-attachments/assets/8825ac22-ed6f-4a87-9a38-ff3b9d34b49a)

Luego, definí las rutas de la API manualmente. Creé dos rutas de ejemplo:

GET /api/hello: Esta ruta responde con el mensaje "Bienvenido a API".
![Image](https://github.com/user-attachments/assets/c716085f-45e1-4b70-a60c-61c5663f8b4b)

GET /api/greet/{name}: Esta ruta permite saludar a un usuario por su nombre. El nombre se pasa como parámetro en la URL.
![Image](https://github.com/user-attachments/assets/aae32500-6acf-47a3-ab0a-c85ece4661fb)

Finalmente, inicié el servidor en el puerto 8080. 
Esto me permitió probar el backend localmente y verificar que las rutas estaban funcionando correctamente. El servidor responde con los mensajes esperados y maneja las solicitudes de manera adecuada.
Ahora este es solo una practica de backend que estara en el proyecto que estare desarrollando con mis compañeros y que si tendra que ver con el proyecto.
el codigo usado para el backend fue el siguiente: 
[codigo backend.txt](https://github.com/user-attachments/files/17036250/codigo.backend.txt)

**Comment by jairoserrano** [comment]
interesante, adelante.

Prioricen UI/UX
