### ISSUE TITLE
definir wireframes de toda la aplicación

### ISSUE THREAD

**Issue by sato165** [ISCOUTB/DH-MI-SUPERTIENDA#3]

**Comment by sato165** [comment]
![Image](https://github.com/user-attachments/assets/976c50e2-6492-4f11-a044-d9aff2a6fbbd)

**Comment by RUBENNN20** [comment]
![Image](https://github.com/user-attachments/assets/241c734f-e2a2-4bc4-a29c-7e1c3d53513d)
![Image](https://github.com/user-attachments/assets/8f939fef-b188-4242-b78c-1c049a67cbc6)
![Image](https://github.com/user-attachments/assets/2e99b1a0-5f37-4f4f-9628-1195799f63a0)

**Comment by jairoserrano** [comment]
adelante
