### ISSUE TITLE
Taller de flutter

### ISSUE THREAD

**Issue by RUBENNN20** [ISCOUTB/DH-MI-SUPERTIENDA#5]

**Comment by RUBENNN20** [comment]
Mi Experiencia con Flutter

Al comenzar con Flutter, lo primero que hice fue descargar el programa desde su sitio web oficial. En este proceso, Flutter me solicitó cumplir con varias condiciones y descargar otros programas necesarios para su correcto funcionamiento, como el SDK de Flutter y algunas dependencias específicas de Android Studio. Estos pasos iniciales fueron fundamentales para configurar el entorno de desarrollo y garantizar que mi sistema fuera compatible con todas las herramientas que utiliza Flutter.

Una vez completada la instalación y la configuración del entorno, decidí usar Visual Studio Code (VS Code) como mi editor de código. Me gusta esta herramienta porque es ligera, personalizable, y cuenta con una excelente integración con Flutter mediante extensiones, lo que facilita mucho la edición y ejecución del código.

Al abrir Flutter por primera vez, el programa me ofreció un proyecto predeterminado que es ideal para comenzar a practicar. Este proyecto me permitió familiarizarme con la estructura del código, la organización de los archivos y el flujo de trabajo en Flutter. A partir de este punto, comencé a hacer cambios pequeños para ver cómo afectaban la interfaz y el comportamiento de la aplicación.

Este proceso inicial fue muy útil para entender la dinámica de Flutter y sus características más básicas, como la creación de widgets y la actualización de la interfaz en tiempo real.

Mi experiencia con Flutter ha sido bastante fluida hasta ahora. La combinación de un buen entorno de desarrollo con herramientas como VS Code y la facilidad que ofrece Flutter para comenzar a crear aplicaciones me ha permitido entender como se crean las aplicaciones web.
[Código base de flutter editado.pdf](https://github.com/user-attachments/files/16968394/Codigo.base.de.flutter.editado.pdf)

**Comment by LuisFelipe634** [comment]
Iniciando con Flutter, la verdad es que la primera impresión es bastante positiva. Lo primero que me llamó la atención fue lo intuitiva que fue, aunque, siendo sincero, la configuración inicial puede parecer un poco tediosa, sobre todo si no estás acostumbrado a trabajar con desarrollo móvil o entornos como Android Studio o Xcode. Sin embargo, una vez que todo está en su lugar, el ambiente de trabajo se siente bastante sólido. 

Algo que me gusto mucho fue el Hot Reload. Básicamente, te permite ver los cambios que haces en tu código casi de inmediato, sin tener que compilar todo de nuevo, y eso es una maravilla. Es como que te da la libertad de experimentar sin la frustración de esperar varios minutos para ver si todo funciona como esperabas.  

Luego está el tema de los widgets. Flutter se basa en ellos para construir todo, y al principio puede parecer un poco raro, pero una vez que lo entiendes, te das cuenta de lo flexibles que son. Todo es un widget, desde un botón hasta un contenedor que agrupa varios elementos.  

Con respecto al leguaje de Dart, No es tan popular como otros lenguajes que he usado antes, pero la verdad es que no me costó mucho acostumbrarme. Si ya tienes experiencia con lenguajes orientados a objetos, te sientes bastante cómodo.
